import type { Metadata } from "next"
import { Nunito } from "next/font/google"
import "./globals.css"
import React from "react"
import {Header} from "@/components/shared"

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin", 'cyrillic'],
  weight: ['400', '500', '600', '700', '800', '900']
})

export const metadata: Metadata = {
  title: "Next Pizza",
  description: "Generated by Next.js",
}

export default function RootLayout({children,}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en" className={nunito.variable}>
      <body className="antialiased">
        <main className="min-h-screen overflow-y-auto">
          <Header/>
          {children}
        </main>
      </body>
      </html>
  )
}
